config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About Us', home_about_path %>

app/views/home/about.html.erb
<h1>About me</h1>
<p>My name is Adesokan Adesayo Joseph and I am building a pinterest clone</p>

app/views/home/index.html.erb
<div class = 'jumbotron'>
    <h1>Welcome to my app</h1>
    <p>It is going to kick all ass...</p>
    <%= link_to 'About Us', home_about_path, class: 'btn btn-default btn-lg' %>
    <%= link_to 'Home', root_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterested</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class = 'container'>
      <%= yield %>
    </div>
  </body>
</html>